persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Permitir conexiones sin autenticación (Simple / Sin ACL)
allow_anonymous true

listener 1883
listener 9001