<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>$(AssemblyName)</PackageId>
    <Title>$(AssemblyName)</Title>
    <Authors>JoeDevSharp</Authors>
    <Description>Net.Mqtt.Infrastructure is a lightweight Reactive Object Mapper (ROM) for MQTT-based applications in .NET. It abstracts MQTT topics as strongly typed, observable entities, enabling developers to handle real-time data streams using LINQ-style syntax and reactive programming patterns.</Description>
    <PackageProjectUrl>https://github.com/JoeDevSharp</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/JoeDevSharp/Net.Mqtt.Infrastructure</RepositoryUrl>
    <PackageIcon>JoeDevSharp.MqttNet.ReactiveBinding.logo.png</PackageIcon>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <PackageTags>mqtt, mqttnet, mqtt5, mqtt-3.1.1, dotnet, worker-service, messaging, infrastructure, cloud-events, cloudevents, mtls, tls, reactive, async-enumerable, typed-messaging, typed-topics, pubsub, event-driven, schema-validation, json-schema, contract-validation, persistent-sessions, reconnection, backpressure, acknowledgement, observability, iot</PackageTags>
    <Version>2.1.0</Version>
    <Copyright></Copyright>
    <PackageOutputPath>bin/nuget</PackageOutputPath>
    <Product>$(AssemblyName)</Product>
    <AssemblyName>$(MSBuildProjectName.Replace(" ", "_"))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="MqttReactiveObjectMapper.csproj.Backup.tmp" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\JoeDevSharp.MqttNet.ReactiveBinding.logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
